In [1]:
import numpy as np

# Creating Arrays

In [2]:
one_dim = np.array([1,3,2])
one_dim

array([1, 3, 2])

In [3]:
two_dim = np.array([[1,3,2],[4,5,6]])
print(two_dim)
print(two_dim.shape)

# three_rows_2_columns = np.array([
    # [[1,2],[3,4]],
#  [[5,6],[7,8]],
#   [[9,10],[11,12]]])
# print(three_rows_2_columns.shape) #(3, 2, 2)

three_rows_2_columns = np.array([[1,2],
                                 [5,6],
                                 [9,10]
                                ])
print(three_rows_2_columns)
print(three_rows_2_columns.shape)

[[1 3 2]
 [4 5 6]]
(2, 3)
[[ 1  2]
 [ 5  6]
 [ 9 10]]
(3, 2)


In [4]:
three_dim = np.array([[1,3,2],[4,5,6],[7,8,9]])
print(three_dim)
print(three_dim.shape)

[[1 3 2]
 [4 5 6]
 [7 8 9]]
(3, 3)


# Array Slicing

## 1D

[start:end:stepsize]



In [5]:
a = np.array((1,2,3,4,5,6,7,8,9))

# to access the 3rd element
a[2]

np.int64(3)

In [6]:
# 2nd to 6th element
print("2nd to 6th element")
print(a[1:6])

# every other element from 2nd to 6th element(not including) i.e skipping elements
print("every other element from 2nd to 6th element(not including)")
a[1:5:2]

2nd to 6th element
[2 3 4 5 6]
every other element from 2nd to 6th element(not including)


array([2, 4])

## 2D

Think like [row,column]

In [7]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# From both elements, return index 2:
b[0:2,2]

array([3, 6])

In [9]:
# From all elements, slice index 1 to index 4 (not included)
b[:,1:4]

array([[2, 3],
       [5, 6],
       [8, 9]])

## 3D

In [10]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
c

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [11]:
# Get specific element (work outside in)
# access the value '7'
c[1,1,0]

np.int64(7)

In [12]:
# change the last row of last and 2nd last list
c[1:,1] = [[22,33],[44,55]]
c

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [22, 33]],

       [[ 9, 10],
        [44, 55]]])

# Initializing arrays

In [13]:
z = np.zeros((4,2))
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
o = np.ones((4,2))
o

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

### Random Number

1.  `np.random.rand()` generates random floating-point numbers from a uniform distribution over the interval [0, 1).

2. `np.random.randint(low, high, size)` generates random integers within the range [low, high) (high is exclusive).

3. `np.random.randn(d0, d1, ..., dn)` generates random numbers from a standard normal distribution (mean=0, standard deviation=1).  Unlike rand, it produces values centered around 0 with both positive and negative results.





In [15]:
# rand gives random samples from a uniform distribution over [0, 1)
r= np.random.rand(2,3)
print(r)
print(r.dtype)

r = np.array(r,dtype = np.float16)
print(r)
print(r.dtype)
# r = np.array(r)

[[0.51164475 0.04919395 0.85999298]
 [0.19203236 0.85345176 0.90196   ]]
float64
[[0.5117 0.0492 0.86  ]
 [0.192  0.8535 0.902 ]]
float16


In [16]:
r= np.random.randint(low=9,high=15,size=(3,2,3),dtype=np.int8)
r

array([[[12, 12, 14],
        [ 9,  9,  9]],

       [[11, 10, 12],
        [13,  9, 14]],

       [[12, 13,  9],
        [11, 14, 13]]], dtype=int8)

In [17]:
r= np.random.randn(2,3)
r

array([[ 0.43576798, -0.64241587,  0.98930718],
       [ 1.06856765, -0.44555522,  0.55313883]])

## Fill single value

In [18]:
an_array = np.array([[2,3,9],[5,7,8]])
an_array.shape

(2, 3)

In [19]:
fl = np.full_like(an_array,21,dtype='int16')
#                     ^
#                     |
# requires an numpy array here not the shape
print(fl)

[[21 21 21]
 [21 21 21]]


In [20]:
f = np.full((2,3),23,dtype='int8')
#           or
# f = np.full(an_array.shape,23,dtype='int8')
f

array([[23, 23, 23],
       [23, 23, 23]], dtype=int8)

In [21]:
pattern = np.ones((5,5))
pattern[1:-1,1:-1] = np.zeros((3,3))
pattern[2,2] = 9
pattern

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# Mathematics

In [22]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [23]:
a + 2

array([3, 4, 5, 6])

In [24]:
a - 2

array([-1,  0,  1,  2])

In [25]:
a * 2

array([2, 4, 6, 8])

In [26]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [27]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [28]:
a ** 2

array([ 1,  4,  9, 16])

In [29]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

## Statistics

In [30]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
np.min(stats)

np.int64(1)

In [32]:
np.max(stats, axis=1)

array([3, 6])

In [33]:
np.sum(stats, axis=0)

array([5, 7, 9])

## Linear Algebra

In [34]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [35]:
# for determinant use

# np.linalg.det(array_name)

# Iterating through array

Instead of using nested loops for printing values in higher dimension arrays we can use `nditer`. We can also change the dataype of the accessed value. using `flags=['buffered'], op_dtypes=['required_data_type']`

In [36]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


Enumerated Iteration Using `ndenumerate()`

In [37]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# Joining Arrays

## Concatenate

In [38]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

print("Array1 :\n",arr1)
print("Array2 :\n",arr2)

print("Concatenating along row(axis=1)")
arr3 = np.concatenate((arr1, arr2), axis=1)#row
print(arr3)

print("Concatenating along column (axis=0)")
arr4 = np.concatenate((arr1, arr2), axis=0)#column
print(arr4)

Array1 :
 [[1 2]
 [3 4]]
Array2 :
 [[5 6]
 [7 8]]
Concatenating along row(axis=1)
[[1 2 5 6]
 [3 4 7 8]]
Concatenating along column (axis=0)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## Stacking

In [39]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

print("Array1 :\n",arr1)
print("Array2 :\n",arr2)

print("Stacking along row(axis=1)")
arr3 = np.stack((arr1, arr2), axis=1)#row
print(arr3)

print("Stacking along column (axis=0)")
arr4 = np.stack((arr1, arr2), axis=0)#column
print(arr4)

Array1 :
 [[1 2]
 [3 4]]
Array2 :
 [[5 6]
 [7 8]]
Stacking along row(axis=1)
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
Stacking along column (axis=0)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [40]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

x = np.hstack((h1,h2))
print(x)
y = np.hstack((h2,h1))
y

[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.]])

In [41]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

### dstack

In [42]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr1D = np.dstack((arr1, arr2))
print(arr1D)

print("2D")
a = np.array([[0, 3],[1, 4],[2, 5]])
b = np.array([[ 6,  9],[ 7, 10],[ 8, 11]])
print("a = ",a)
print("b = ",b,"\nDstack:")
print(np.dstack([a,b]))

[[[1 4]
  [2 5]
  [3 6]]]
2D
a =  [[0 3]
 [1 4]
 [2 5]]
b =  [[ 6  9]
 [ 7 10]
 [ 8 11]] 
Dstack:
[[[ 0  6]
  [ 3  9]]

 [[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]]


# Difference betn concatenate and stack

In [43]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

print("Array1 :\n",arr1)
print("Array2 :\n",arr2)

print("Concatenating along row(axis=1)")
arr3 = np.concatenate((arr1, arr2), axis=1)#row
print(arr3)

print("\nhStack")
arr3 = np.hstack((arr1, arr2))
print(arr3)

print("Stacking along row(axis=1)")
arr3 = np.stack((arr1, arr2), axis=1)#row
print(arr3)


print("Concatenating along column (axis=0)")
arr4 = np.concatenate((arr1, arr2), axis=0)#column
print(arr4)

print("\nvStack")
arr4 = np.vstack((arr1, arr2))
print(arr4)

print("Stacking along column (axis=0)")
arr4 = np.stack((arr1, arr2), axis=0)#column
print(arr4)

Array1 :
 [[1 2]
 [3 4]]
Array2 :
 [[5 6]
 [7 8]]
Concatenating along row(axis=1)
[[1 2 5 6]
 [3 4 7 8]]

hStack
[[1 2 5 6]
 [3 4 7 8]]
Stacking along row(axis=1)
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
Concatenating along column (axis=0)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

vStack
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Stacking along column (axis=0)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Array splitting

In [44]:
arr = np.arange(1,11)
print(type(arr))
print(arr)

newarr = np.array_split(arr, 3)
print(type(newarr))
print(newarr)

<class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10]
<class 'list'>
[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]


In [45]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3, axis=1)
print(newarr)

print("Axis 0")
newarr = np.array_split(arr, 3)#axis = 0
print(newarr)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int64)]
Axis 0
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


# Searching arrays

## where

In [46]:
import numpy as np

arr = np.array([10, 14, 93, 41, 8, 7])
x = np.where(arr%2 == 1)
print(x)

(array([2, 3, 5]),)


## searchsorted

In [47]:
import numpy as np

arr = np.array([6, 7, 8, 9])

print(np.searchsorted(arr, 7, side='right'))
print(np.searchsorted(arr, 7))

2
1


In [48]:
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])

print(x)#[1 2 3]
# it doesnt means all 2,4,6 at once but if we were to insert 2 only it should be in index 1.
# if inserting 4 only then at index 2 and so on.
# this explanation makes more sense for the below code

np.searchsorted(arr, [8,9])# array([4, 4])
# it doesn't mean 8 and 9 both be inserted in index 4


[1 2 3]


array([4, 4])

# Sorting

In [49]:
#sorting 2D array
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

arr = np.array([True, False, True])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
[False  True  True]


# Filter

Its boolean masking

In [50]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


above can also be done as:

In [51]:
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [52]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
